version: "3"

services:
  backend:
    container_name: galactica
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: /bin/sh -c "npm i; npx prisma generate; npm run start:dev"
    ports:
      - "8000:8000"
    volumes:
      - node_modules:/app/node_modules
      - ./:/app:z
    environment:
      - DATABASE_URL
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: galactica-db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
  node_modules:
